# Generated by Django 6.0 on 2026-01-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtasks',
            name='priority',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kanban_app.taskpriority'),
        ),
        migrations.AlterField(
            model_name='dashboardtasks',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kanban_app.taskstatus'),
        ),
    ]
