# Generated by Django 6.0 on 2026-01-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtasks',
            name='priority',
            field=models.CharField(choices=[('low', 'low priority'), ('medium', 'medium priority'), ('high', 'high priority')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='dashboardtasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'), ('review', 'review'), ('done', 'done')], default='to-do', max_length=15),
        ),
        migrations.RenameField(
            model_name='dashboardtasks',
            old_name='assigned',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='dashboardtasks',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
        migrations.AddField(
            model_name='dashboardtasks',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban_app.boards'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='kanban_app.dashboardtasks')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskPriority',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
