# Generated by Django 6.0 on 2026-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_dashboardtasks_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtasks',
            name='priority',
            field=models.CharField(choices=[('low', 'low priority'), ('medium', 'medium priority'), ('high', 'high priority')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='dashboardtasks',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=15),
        ),
        migrations.DeleteModel(
            name='TaskPriority',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
