# Generated by Django 6.0 on 2026-01-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_alter_dashboardtasks_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtasks',
            name='status',
        ),
    ]
