# Generated by Django 6.0 on 2026-01-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_remove_dashboardtasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardtasks',
            old_name='assigned',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='dashboardtasks',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
