# Generated by Django 6.0 on 2026-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_rename_assigned_dashboardtasks_assignee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'), ('review', 'review'), ('done', 'done')], default='to-do', max_length=15),
        ),
    ]
