# Generated by Django 6.0 on 2026-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_dashboardtasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtasks',
            name='board',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
