# Generated by Django 6.0 on 2026-01-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0007_dashboardtasks_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtasks',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban_app.boards'),
        ),
    ]
