# Generated by Django 6.0 on 2026-01-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
