# Generated by Django 6.0 on 2026-01-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0010_rename_comment_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
    ]
