# Generated by Django 6.0 on 2026-01-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0011_rename_author_comment_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
    ]
